version: "3"
services:
  api:
    build: api/.
    depends_on:
      - postgres
    env_file: .env
    environment:
      DB_USER: "${DB_USER}"
      DB_PASS: "${DB_PASS}"
      DB_NAME: "${DB_NAME}"
      NODE_ENV: production
    ports:
      - "3000:3000"
    volumes:
      - .:/api
      - /api/node_modules

  dashboard:
    build: dashboard/.
    depends_on:
      - api
    environment:
      NODE_ENV: production
    ports:
      - "3001:80"
    volumes:
      - .:/app
      - /app/node_modules

  postgres:
    image: postgres:10.4
    ports:
      - "35432:5432"
    env_file: .env
    environment:
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASS}"
      POSTGRES_DB: "${DB_NAME}"