version: "3"
services:
  api:
    build: api/.
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://user:pass@postgres:5432/db
      NODE_ENV: production
    ports:
      - "3000:3000"
    volumes:
      - .:/api
      - /api/node_modules

  dashboard:
    build: dashboard/.
    depends_on:
      - api
    environment:
      NODE_ENV: production
    ports:
      - "3001:80"
    volumes:
      - .:/app
      - /app/node_modules

  postgres:
    image: postgres:10.4
    ports:
      - "35432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: db
